import React, { Component } from "react";
class Ecommerce extends Component {
  render() {
    return (
      <div className="contain">
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
        <li>hey world</li>
      </div>
    );
  }
}

export default Ecommerce;
